### ISSUE TITLE
Need help mounting E01 file on cygwin

### ISSUE THREAD

**Issue by Magister-Machinis** [libyal/libewf-legacy#21]
Hello,

I built the source code according to the guide for cygwin/gcc and it appears to spit out the expected files. Running help flags of ewfmount appears to produce the expected output, but actually attempting to mount a file produces the below error. I get the same error in both a regular and elevated prompt. Any thoughts on what I could be missing? The image is in multiple fragments on a network share, would these potentially cause problems?

Thank you
![image](https://user-images.githubusercontent.com/30908581/187206001-35f5de64-3a1d-40e2-95df-cf4d9ffd28de.png)

**Comment by joachimmetz** [comment]
try cygwin paths

**Comment by Magister-Machinis** [comment]
Similar errors, but it seems to be having issues accessing the file. Could this be a cygwin permission thing?
![image](https://user-images.githubusercontent.com/30908581/187462546-065d41a7-906c-4fb8-ae2e-f7a39717edcc.png)

**Comment by joachimmetz** [comment]
@Magister-Machinis try putting the `-v` before the path arguments

**Comment by Magister-Machinis** [comment]
Similar errors appear to pop up (see below)
![image](https://user-images.githubusercontent.com/30908581/187745824-673fd649-6070-44e8-bf9e-c2a89d3a6d85.png)
However I get something new if I try mounting an image thats on an external hdd rather than a network share. Did I miss something duration compilation?
![image](https://user-images.githubusercontent.com/30908581/187746112-40832d75-67c7-4479-8406-12b67f8a2af7.png)

**Comment by joachimmetz** [comment]
is `//<IP>` a local path or is that an UNC path? the latter is not supported. 

the second warning means you did not compile ewfmount with fuse or DokanY support, so no subsystem to do the actual mount see https://github.com/libyal/libewf/wiki/Mounting#mounting

**Comment by Magister-Machinis** [comment]
Understood, thanks for all your patience with this! I'm on EST so I'll put this through its paces in the AM and let you know how it goes.

**Comment by Magister-Machinis** [comment]
Definitely making progress!
I added cygfuse to the cygwin setup and rebuilt, got the below error.
![image](https://user-images.githubusercontent.com/30908581/188002889-dbbea6ff-8d7a-4e4f-87c9-6e59b70d0e72.png)
Looking around it seemed like it was referencing https://github.com/winfsp/winfsp, so downloaded and installed just the core and got:
![image](https://user-images.githubusercontent.com/30908581/188003036-c3cb7bf9-406c-421c-8706-bc8638b78fa6.png)
Adding the fuse for cygwin component resulted in:
![image](https://user-images.githubusercontent.com/30908581/188003166-28fda345-479b-4e39-af94-6131dcfd4f02.png)
Is there a specific version or variant of winfsp I should look for? It seems the above installs a 32 bit version of winsfp which I suspect to be the cause here.

**Comment by joachimmetz** [comment]
> Looking around it seemed like it was referencing https://github.com/winfsp/winfsp, so downloaded and installed just the core and got:

Please don't download random binaries from the Internet. Make sure you have a legitimate and correct one for your set up. I suspect the issue you are seeing is due to an incomplete installation of cygfuse

**Comment by Magister-Machinis** [comment]
Ah, to be clear that is the repo recommended by cygfuse on their respective
repo. I'll poke at it a bit more and see if I've missed something. Thanks!
