### ISSUE TITLE
State of EWF2/bzip2 support (and documentation)

### ISSUE THREAD

**Issue by JustMyGithub** [libyal/libewf-legacy#22]
ewfacquirestream -h
says bzip2 is supported only for EWF2 formats. According to the readme my understanding is that EWF2 formats are not supported (which would mean pbzip2 is not supported as well), but if that was true: why is bzip2 "supported" anyway? (maybe only for decryption like for mount ?)

**Comment by JustMyGithub** [comment]
Thx, that is what I expected.
(and incredibly fast reply!)

**Comment by joachimmetz** [comment]
https://github.com/libyal/libewf-legacy/commit/e8a255a2e1532a4581f611cc605773c117034ece
