### ISSUE TITLE
Is 20140816 still a pre-release

### ISSUE THREAD

**Issue by carlsmedstad** [libyal/libewf-legacy#26]
Hey :wave: Arch Linux maintainer here.

Is the release [20140816](https://github.com/libyal/libewf-legacy/releases/tag/20140816) still considered a pre-release? If so, can you make it a pre-release instead of a proper release in GitHub?

Thanks!

**Comment by joachimmetz** [comment]
thanks for flagging, metadata was set to release (which I would say is leading), comment was incorrectly saying it is a pre-release, should be addressed now.
