### ISSUE TITLE
How to build libewf dll for 64 bit?

### ISSUE THREAD

**Issue by RandomGrep** [libyal/libewf-legacy#27]
Dear @joachimmetz ,
I went through [https://github.com/libyal/libewf-legacy/issues/10] , I tried building for 64 bit I am getting error at libcfile's makefile and getting exit by status 1 every time, I am using MSYS2 64 bit to build it.
I don't know what is going wrong. I tried to follow the build instruction as well as the steps from the issue 10 but I am not getting anywhere... As discussed earlier in the issues, downloading the libewf.dll from internet is not a good idea either!
Can you please help me with building issue?

**Comment by joachimmetz** [comment]
@sk-zeeshan can you provide more details about the issue you are running into?

Also see https://github.com/libyal/libewf/wiki/Building or https://www.nuget.org/packages/libewf/

**Comment by joachimmetz** [comment]
> Can you please provide me updated steps to build it?

I'm unable to help you if you don't provide a step-by-step break down of what you are doing and what actual error messages/warning you are getting

**Comment by joachimmetz** [comment]
it is very hard for me to read the screenshot, so standard questions:

* did you build for the right WINAPI version?
* are you missing visual C/C++ runtime ?

**Comment by joachimmetz** [comment]
> I just want to use it with .Net(C#)!!!

This is the first time you mention building for dotnet, why not start with that?
Might be better to build with visual studio and the dotnet bindings that are provided.

> I am just lost now!!!

As I indicated I'm unable to help you if you don't provide a step-by-step break down of what you are doing and what actual error messages/warning you are getting. The more specific you can be the better I can guide you, otherwise you'll have to navigate the ambiguity yourself.

**Comment by joachimmetz** [comment]
> Should I have used CPPFLAGS=-DWINVER=0x0A00, because I am building and going to use the dll in windows 10?

WINVER is used to set the minimum compatible version of the WinAPI, using 5.1 on Windows 10 should be fine.

> To use it in .Net with C# are there any different steps to follow, or I can use this directly(maybe by making a wrapper)?

There is a wrapper, I mentioned this to you in https://github.com/libyal/libewf-legacy/issues/27#issuecomment-2561153301

**Comment by joachimmetz** [comment]
> I didn't see the wrapper in the documentation!

Could be the documentation is not perfect, the code is here https://github.com/libyal/libewf-legacy/tree/main/ewf.net should build with visual studio. Based on the CI tests should still build but note given I have no use for it might need some tweaking. Also see: https://ci.appveyor.com/project/libyal/libewf-legacy/builds/51212876/job/cqq1ik25ty4jgaia#L198
