### ISSUE TITLE
How to write a "logical" volume image?

### ISSUE THREAD

**Issue by samicheema** [libyal/libewf-legacy#7]
Hi,

I am using this library for physical drive compression and its working fine. Now, I want to use this library for volume based(logical drives) compression. Can somebody help me in it. 

Either I have to update the library or I just have to set the parameters.

Your support in this regard will be highly appreciated.

Thanks & Regards
Sami Cheema

**Comment by samicheema** [comment]
Thanks for the response @joachimmetz, I tried to get the volume based imaging, by setting the volume type "logical". But it generates the whole physical drive image instead of a drive wise. Could you please help me in it. Thanks

**Comment by joachimmetz** [comment]
setting logical or physical is only changing the metadata, you'll also need to the right data in the EWF files. e.g. instead of `/dev/sda` (physical) you read `/dev/sda1` (logical)

**Comment by samicheema** [comment]
Please guide me where we can set this? Thanks

**Comment by joachimmetz** [comment]
> Please guide me where we can set this?

You cannot set this in libewf, this out of scope of the library. The library only provides you access to the EWF storage format. What and how you put into it or get out of it, is up to the application code that uses the library.

**Comment by samicheema** [comment]
@joachimmetz, I have downloaded [this ](https://github.com/libyal/legacy/blob/master/libewf/libewf-20140608.tar.gz )library. Where in _libewf-20140608\ewftools\_ did by setting "_option_target_filename_" or "_option_toc_filename_" with complete logical derive path could resolve my issue?

**Comment by joachimmetz** [comment]
ewfacquire is part of the (ewf)tools not the library. 

option_toc_filename is used for the file that contains the table of contents for optical disks. So this it not relevant for storing a volume image in an EWF file.

option_target_filename the resulting EWF file set name. This is needed for both physical and logical images. You'll need this anyway but not specifically for storing a volume image in an EWF file. 

what you likely want is similar to:
`ewfaqcuire -M physical /dev/sda`
`ewfaqcuire -M logical /dev/sda1`

**Comment by samicheema** [comment]
@joachimmetz, thanks for the prompt responses, this resolve my issue. 

Just one more question did the "empty-block" and "zero-block" are same thing?

**Comment by joachimmetz** [comment]
A zero-block is an empty-block filled with 0-byte values

**Comment by samicheema** [comment]
Alright. Thanks (y)

**Comment by joachimmetz** [comment]
Question answered, closing issue
